name: Testing
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - name: Envoi du code coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./coverage/Icov-report/